name: Oomnitza Auth Check

on:
  workflow_dispatch:

jobs:
  auth:
    name: Test Oomnitza Authentication
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run auth test
        env:
          OOMNITZA_URL: ${{ secrets.OOMNITZA_URL }}
          OOMNITZA_API_TOKEN: ${{ secrets.OOMNITZA_API_TOKEN }}
          OOMNITZA_VERIFY_SSL: ${{ secrets.OOMNITZA_VERIFY_SSL }}
        run: python scripts/test_oomnitza_auth.py
